/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.example.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core")
}

application {
    // Define the main class for the application.
    mainClass.set("com.example.app.AppKt")
}
