/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm")
    id("info.solidsoft.pitest")
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    constraints {
        // Define dependency versions as constraints
        implementation("org.apache.commons:commons-text:1.10.0")
        implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.2")
    }

    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.2")
    testImplementation("org.assertj:assertj-core:3.24.2")

    // Required for pitest. A future version of the pitest gradle plugin may
    // make this unneccesary.
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.9.2")

    pitest(Constants.Plugins.pitestKotlin)
    pitest(Constants.Plugins.pitestBase)
}

pitest {
    targetClasses.set(listOf("com.example.*"))
    pitestVersion.set("1.15.3")
    junit5PluginVersion.set("1.2.0")
    outputFormats.set(listOf("XML", "HTML"))
    exportLineCoverage.set(true)
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

